spring.application.name=realinvoice

# 1. MSSQL Veritaban? Ba?lant? Ayarlar?
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=InvoiceDb;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Hibernate / Dialect Ayarlar? (Hatan?n do?rudan panzehiri)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true